### ISSUE TITLE
Helper working, but 'Run' not working (Win10 x64)

### ISSUE THREAD

**Issue by neRok00** [iron4umx/yt_dlp_firefox#49]
I have got the firefox addon working with the helper thanks to your install batch file. I already have yt-dlp on my PATH, so it didn't download it. I did edit the json file to point to tyilo package.

The problem is I get the error `Got exception communicating with helper: Error: An unexpected error occurred`. Not a very helpful message. I found the first part of the error message is by the FF addon, line 109 in background.js. The second part is not an error message from the helper, just the JS error caught.

I went to the helper and wrapped `p = run(...` block with a try catch, something like this;

    try:
        p = run(
            ["yt-dlp.exe" ....
            if ...
            else ...
    except Exception as e:
        reply = {
            "success": False,
            "error": "Run error: " + str(e),
        }

Now the exception in python gets passed along as a message, which is `[WinError 2] The system cannot find the file specified`.

That's as far as I've got so far. I'm guessing the error is because it's looking for exe in folder, not exe on PATH?

BTW, when this addon works, does a terminal or something appear for the active yt-dlp program? I'm just wondering how a recording of a live stream can be stopped (ie, not a fixed length video stream with an obvious end).

**Comment by iron4umx** [comment]
@neRok00 Hi there! it seems that the helper can not find your installation of yt-dlp, however SETUP.bat did found your instance that is why it skipped the download and installation part, so as long as yt-dlp is defined in PATH there should be no problems since the helper is pretty much executing the command in the terminal yt-dlp [url] being the url defined by the right click contextual menu's taget at the time.

At the time I can only think of uninstalling your current yt-dlp instance and then rerun the SETUP.bat and reinstall the helper alongside yt-dlp.exe but in theory you are not suposed to have any problems as long as you can execute yt-dlp from anywhere in your CMD terminal, this is weird, I am going to try to recreate the problem and see what I can come up with.

When the add-on is working, lets say you go to youtube and right click on a live stream and click on download with yt-dlp a pop up message will appear stating that it is downloading the media, when the media finishes downloading another pop up message will appear stating that it finished downloading, meanwhile, you can click on the button for this add-on located in the upper right side of your Firefox right next to your menu button (make sure you have pinned the button to your task bar or it may be hidden on the add-on button) so click on the button with the download arrow icon and a pop up will appear with information on current and past downloads, there is no terminal that pops open or any further means of inputting parameter commands to the yt-dlp engine at this moment for this add-on, in the case of live streams yt-dlp has extra parameters that can be used to either download from the begining and so on but at this time this add-on is lacking any means to input the download parameters.

Let me know if uninstalling your yt-dlp and reruning SETUP.bat and reinstall did the trick for you, like I say this is kind of weird and it should be working fine.

**Comment by iron4umx** [comment]
@neRok00 So I ran SETUP.bat with yt-dlp.exe installed on a different folder from the helper (I added the path of the folder containing yt-dlp.exe to the PATH), since yt-dlp.exe was already installed SETUP.bat skipped downloading and installing it, the add-on worked fine, no issues here (using tyilo's add-on and modifiying the helpers .json file to point to tyilo's package) thus we can say that the helper looks for yt-dlp.exe on the PATH and not the same folder where the helper is installed, I only made SETUP.bat download and install yt-dlp.exe on the same folder as the helper for convenience, yt-dlp.exe can be installed on any folder as long as it is included on the PATH.

This being said, I did notice something, right after adding the folder to the PATH i tried to open yt-dlp.exe on the CMD, the system did not recognized the command, this is because you need to reboot the system in order for the changes to fully register (part of the same reason why many programs require a system reboot after installation) this being said, if this was your case then you might be a system reboot away from having the add-on working this is the only scenario where I think the issue replicates: you downloaded yt-dlp.exe added to PATH then proceeded to install yt-dlp-firefox on your firefox, then you modified the .json of the helper then you ran SETUP.bat and in deed the helper works, but yt-dlp.exe is unreachable system wide because the system needs a reboot, let me know if this helps.

**Comment by neRok00** [comment]
> you need to reboot the system in order for the changes to fully register

Yes, this was the problem. I added it to the PATH without rebooting and presumed it was working fully because it was working in powershell/cmd (hence the install batch file ran), but evidently that was not enough for python to be happy. Rebooted and now it works. Thanks.

**Comment by neRok00** [comment]
I don't know if you plan to implement more features to this addon to iron4umx? But I've just done a quick hack job to suit my needs, which were enabling a few basic options and streaming support (all I want is to right-click download, then have a terminal pop up that I can cancel live stream from). I did it all via the helper files though, rather than getting in to the browser/javascript. So even if this addon never gets advanced further, maybe this janky code will help someone?

First of all I replaced the run yt-dlp with a command to run a powershell script;

        p = run(
            ["powershell", "-file", "yt-dlp_helper.ps1", "-url", url],
            creationflags=subprocess.CREATE_NEW_CONSOLE,
        )

That ps1 file is in the same folder with the py file. Here's an example of what can be achieved in that file;

    param(
        [Parameter(Mandatory=$True, Position=0, ValueFromPipeline=$false)][System.String]$url
    )
    "===== YT-DLP Helper ====="
    $res_choice = $host.UI.PromptForChoice("Preferred Video Size", "Choose one;", [System.Management.Automation.Host.ChoiceDescription[]] @("&0: Default", "&1: 1080", "&2: 720", "&3: 480"), 3)
    Switch ($res_choice){
        0 {$res=""}
        1 {$res="-S res:1080"}
        2 {$res="-S res:720"}
        3 {$res="-S res:480"}
    }
    $arg_list = @(
        $res,
        "--paths", "%userprofile%\Videos\"
        "--restrict-filenames",
        "--no-part",
        "--user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0",
        $url
    )
    yt-dlp @arg_list
    Read-Host -Prompt "YT-DLP exited. Press Enter to close"

I also disabled the json related code after `if p.returncode == 0:` because the terminal has different output, so now its just `reply = {"success": True}`. It's good enough for all I care.

But that's it. I right click > download in firefox, then a terminal pops up, I make my selections, and it starts downloading. Then to stop I do ctrl+c on the terminal (which is how I stop live streams manually when using yt-dlp directly anyway).
